# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Returns the powerhell command for downloading file, requires hash to form command
#
#
Puppet::Functions.create_function(:'pget::build_header_cmd') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    raise(Puppet::ParseError, "build_header_cmd(): Wrong number of arguments " +
        "given (#{args.size} for 1") if args.size != 1
    @@cmd = ""

    @@header = args[0]
    debug("#{@@header} was passed to function")
    @@header.each do |k, v|
      @@cmd += "\$wc.Headers.Add('#{k}','#{v}');"
      debug("#{@@cmd} is built so far")
    end
    return @@cmd
  
  end
end
